run:
  timeout: 3m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - typecheck

issues:
  exclude-dirs:
    - pb_data
    - web
    - server/web/dist
